apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-web-server-postgresql-pvc
  labels:
    app: {{ include "my-web-server.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
