replicaCount: 1

image:
  repository: sdikman/custom-web-server-rootless
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccountName: my-web-server-sa

service:
  type: ClusterIP
  port: 8080

route:
  enabled: true
  host: ""

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: mypassword
  postgresqlDatabase: mydatabase
  persistence:
    enabled: true
    size: 1Gi

resources:
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "150m"
    memory: "200Mi"

securityContext:
  runAsUser: 1000960000
  fsGroup: 1000960000
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - "ALL"
  seccompProfile:
    type: "RuntimeDefault"
